### ISSUE TITLE
우분투 15.10 qtbase-abi-5-4-* 패키지 오류

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom#19]
_From @parkmino on October 23, 2015 4:53_

방금 우분투 판올림을 했는데, 위 패키지가 없다며 실행이 되지 않네요.
수정 부탁 드립니다.

_Copied from original issue: cogniti/dasom#19_

**Comment by ghost** [comment]
우분투 15.10 이 정식 버전으로 나왔군요.
재컴파일해야 될 겁니다.
버추얼박스에 깔고 deb 만들려면 시간 좀 걸립니다.
오늘은 어렵고 내일쯤 파일 올라갈 겁니다.
알려드리겠습니다.

**Comment by ghost** [comment]
_From @parkmino on October 23, 2015 12:48_

네, 그냥 컴파일만 새로하면 되는 거 였군요.
방금 다솜 컴파일해서 쓰고 있습니다.
시간 나실 때 다른 분들을 위해서 설치 파일 올려주시면 감사하겠습니다.

**Comment by ghost** [comment]
dasom 1.0 소스로 우분투 15.10에서 컴파일해보니 에러가 나는군요. 그 에러는 이후 커밋에서 해결되었습니다. 나중에 릴리즈 작업할 때 우분투 15.10 패키지 만들어야겠습니다.

**Comment by ghost** [comment]
_From @iyagicom on November 3, 2015 12:18_

다솜 1.0.1
우분투 15.04에서 qtbase-abi-5-4-2 의존성 에러 나오네요

**Comment by ghost** [comment]
재컴파일해야 될 거 같네요

**Comment by cogniti** [comment]
This issue was moved to dasom-im/dasom#1

**Comment by ghost** [comment]
프레임워크로부터 엔진 분리 작업 때문에 @iyagicom 릴리즈 작업을 지금은 할 수 없습니다.
아래 명령으로 deb 파일을 직접 만드실 수 있습니다.

```
git clone https://github.com/dasom-im/dasom.git
cd dasom
git checkout 2300f58827d2f7be874965083ac2bc97d5ca737d
dpkg-checkbuilddeps
```

없다는 패키지 모두 설치 후에

```
dpkg-buildpackage -b
ls .. # deb 파일이 만들어졌는지 확인 후 설치하시면 됩니다
```

**Comment by ghost** [comment]
@iyagicom
우분투 15.04 용 deb 파일 올려놓았습니다.
https://github.com/dasom-im/dasom/releases/tag/1.0.1
