### ISSUE TITLE
Thunderbird 계정 등록 시 비밀번호 입력이 되지 않습니다.

### ISSUE THREAD

**Issue by janghe11** [dasom-im/dasom#27]
현재 사용 환경 : Ubuntu 15.10 64bit
테스트 PC : Lenovo laptop, LG laptop 2대
사용 입력기 : dasom 1.0.1 for Ubuntu 15.10 debian package
Mozilla Thunderbird 기본 클라이언트에서 메일 계정 설정을 하려고 하면 비밀번호 입력이 되지 않습니다.
한영 전환을 하여 입력하려고 하면 한 글자만 입력이 되고 나머지는 입력이 되지 않습니다.
완료를 누르면 나오는 Google 계정 입력 창에서도 비밀번호 입력이 되지 않았습니다.
아쉽게도 어떠한 이유로 작동이 되지 않는지는 알아내지 못했습니다.

![image](https://cloud.githubusercontent.com/assets/2038544/11317241/747e6002-906a-11e5-8d04-4ec7a9aa9108.png)

![image](https://cloud.githubusercontent.com/assets/2038544/11317262/61a58c48-906b-11e5-8537-dc34d95574a5.png)

**Comment by ghost** [comment]
해당 버그는 https://github.com/dasom-im/dasom/commit/a63e8a13d6a532f000139e0af28823d76b445db0 에서 고쳤습니다.
불편하실텐데 조만간 릴리즈를 준비하도록 하겠습니다.
관련 이슈 https://github.com/dasom-im/dasom/issues/28

**Comment by ghost** [comment]
다솜 1.1, 다솜 정음 1.1 을 릴리즈하였습니다.
https://github.com/dasom-im/dasom/releases/tag/1.1
https://github.com/dasom-im/dasom-jeongeum/releases/tag/1.1
각각 다운받아서 설치하시면 되겠습니다.
