### ISSUE TITLE
데비안8 64bit eclipse 에서 수정을 위해서 중간 위치에 한글 한글자 입력후 오른쪽 화살키 입력시 입력한 글자가 사라집니다. 

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom#29]
_From @SinnoriTeam on November 15, 2015 5:50_

데비안8 64bit eclipse 에서 수정을 위해서 중간 위치에 
한글 한글자 입력후 오른쪽 화살키 입력시 입력한 글자가 사라집니다. 

원문 : "값 설치경로에 맞게 변경한다."
원하는 결과 : "값들 설치경로에 맞게 변경한다."
실제 결과 : "값 설치경로에 맞게 변경한다." 

커서 위치는 "설" 자와 "치" 자 사이에서 깜박입니다.

터미널이나 iceweal 에서는 eclipse 와 같은 현상 없이 잘 동작합니다.
터미널이나 iceweal 에서도 잘 동작하는거 봐서는 
이클립스쪽 문제가 아닌가 조심스럽게 추정해 보지만
그래도 관련 내용이라 이곳 이슈에 올려봅니다.

```
----------- uname -a 결과
Linux madang01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
-----------
Eclipse Platform  Version: 3.8.1
```

_Copied from original issue: dasom-im/dasom-jeongeum#2_

**Comment by ghost** [comment]
fcitx, imhangul 에서 해당 증상 나타나지 않음.
이클립스 실행하여 ㄱ 입력후 화살표 키 누를 경우,
다솜 gtk im 모듈이 아래처럼 실행되는데 이상은 없어 보입니다.

```
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FOCUS_IN, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FOCUS_IN_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_RESET, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_RESET_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FILTER_EVENT, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_PREEDIT_START, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_PREEDIT_START_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_PREEDIT_CHANGED, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_GET_PREEDIT_STRING, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_GET_PREEDIT_STRING_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_SET_CURSOR_LOCATION, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_SET_CURSOR_LOCATION_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_PREEDIT_CHANGED_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FILTER_EVENT_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FILTER_EVENT, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FILTER_EVENT_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FILTER_EVENT, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_COMMIT, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_SET_CURSOR_LOCATION, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_SET_CURSOR_LOCATION_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_COMMIT_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_PREEDIT_CHANGED, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_GET_PREEDIT_STRING, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_GET_PREEDIT_STRING_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_GET_PREEDIT_STRING, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_GET_PREEDIT_STRING_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_PREEDIT_CHANGED_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_PREEDIT_END, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_PREEDIT_END_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FILTER_EVENT_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FILTER_EVENT, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FILTER_EVENT_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FOCUS_OUT, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FOCUS_OUT_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FOCUS_IN, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FOCUS_IN_REPLY, fd: 126
(Eclipse:5930): dasom-DEBUG: send: DASOM_MESSAGE_FOCUS_OUT, fd: 126
(Eclipse:5930): dasom-DEBUG: recv: DASOM_MESSAGE_FOCUS_OUT_REPLY, fd: 126
```

hodong@debian:~/dasom-jeongeum$ git diff

```
diff --git a/src/dasom-jeongeum.c b/src/dasom-jeongeum.c
index e6d1818..e23f4cc 100644
--- a/src/dasom-jeongeum.c
+++ b/src/dasom-jeongeum.c
@@ -377,6 +377,13 @@ dasom_jeongeum_filter_event (DasomEngine     *engine,
       dasom_jeongeum_filter_leading_consonant (engine, target, keyval))
     return TRUE;

+  if (event->key.keyval == DASOM_KEY_Left || event->key.keyval == DASOM_KEY_space)
+  {
+    g_message ("in case of DASOM_KEY_Left hangul_ic_process returns %d", retval);
+    dasom_jeongeum_reset (engine, target);
+    return TRUE;
+  }
+
   retval = hangul_ic_process (jeongeum->context, keyval);

   ucs_commit  = hangul_ic_get_commit_string  (jeongeum->context);
```

이런 코드를 넣어서 확인해봤는데,
조합 중일 때 스페이스 누를 경우 출력됨.
조합 중일 때 왼쪽 화살표 누를 경우 출력되지 않음.
이클립스 문제입니다.

이유는 모르겠으나 아래처럼 해도 회피가 되지 않습니다.
hodong@debian:~/dasom$ git diff

```
diff --git a/modules/clients/gtk/im-dasom.c b/modules/clients/gtk/im-dasom.c
index 57aa18e..9219383 100644
--- a/modules/clients/gtk/im-dasom.c
+++ b/modules/clients/gtk/im-dasom.c
@@ -138,6 +138,10 @@ on_gdk_x_event (XEvent            *xevent,
       if (context->is_hook_gdk_event_key)
       {
         DasomEvent *d_event = translate_xkey_event (xevent);
+
+        if (d_event->key.keyval == DASOM_KEY_Left)
+          dasom_im_reset (context->im);
+
         retval = dasom_im_filter_event (context->im, d_event);
         dasom_event_free (d_event);
       }
```

**Comment by ghost** [comment]
Bug 371397 - When I enter the Korean sentence : Last character is gone.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=371397

**Comment by ghost** [comment]
@SinnoriTeam 제가 작성한 글을 영어로 번역해서 https://bugs.eclipse.org/bugs/show_bug.cgi?id=371397 이곳에 이어서 버그 리포트 보내세요.

**Comment by ghost** [comment]
어플 버그를 회피하는 코드(workaround code)를 넣는 이유는 어플을 당장 사용해야 하는데 어플 버그가 고쳐지고 릴리즈되어 배포판에 탑재되기까지 시간이 필요하기 때문입니다.
어플 버그가 고쳐지려면 어플 개발자에게 버그 보고를 해서 알려야 합니다. 누구나 보고할 수 있습니다. 그걸 제가 반드시 해야 하는 이유는 없습니다.

https://forum.ubuntu-kr.org/viewtopic.php?f=4&t=28348&start=30#p125899

그리고 우분투 포럼에 땜빵 입력기라고 폄하하면서 이클립스 개발자가 몰라서 버그 리포트를 하면 무슨 소용이 있겠냐고 추측성 글을 써놓으셨던데... 기본적인 예의는 지키셨으면 좋겠습니다.
게다가 '입력기 선구자들이 땜빵하지 말고 싸워 클라이언트 수정을 이끌었다면...' 하면서 이런 식으로 개발자에게 부담이 가는 글을 작성하여, 제가 이클립스 프로젝트에 버그 리포트를 하게끔 하려는 전략 같은데... 그거는 사용자분이 직접 하셔야 하는 겁니다. 그걸 왜 제탓으로 돌리는 겁니까. 그러실 것 같으면 다솜 입력기를 사용하지 마십시오.
그리고 이슈 내용을 우분투 포럼에 흘려서 개발자에게 부담 또는 책임을 지우는 듯한 글을 작성하지 마십시오. 오픈소스 프로그램을 사용하면서 할 말이 있고 못 할 말이 있습니다.
오픈소스 프로그램은 기본적으로 보증 책임이 없습니다. NO WARRANTY 입니다.

**Comment by ghost** [comment]
한국 사용자분들이 버그 보고를 하지 않고 남탓해서 한글 입력 버그가 5년 이상 방치되는 것입니다. 거듭 말씀드리지만, 입력기 개발자 탓이 아닙니다. @SinnoriTeam 님 탓입니다. 아직까지도 버그 보고를 안 하셨던데 남탓할 시간에 이클립스 프로젝트에 보고해주세요.
위에 제가 자세히 설명을 드렸기 때문에 몰라서 못한다는 것은 핑계입니다. 그리고 한글 입력 버그가 확인된 프로그램이 10종이 넘어갑니다. 입력기 개발자가 각 어플 프로젝트에 버그 보고하기를 바라지 마십시오. 저 혼자 보고하다보면 버그 보고에만 최소 1년이 넘게 걸립니다. 게다가 저는 그 어플들을 사용하지도 않습니다.
따라서 각 사용자분들이 하시는게 맞는 겁니다.
다솜 입력기가 과도기 프로젝트도 아니고 X Window 도 나온지가 수십년이 지났습니다. 이 버그는 XIM 과는 관련이 없습니다.
그리고 회피 코드(workaround)에 대해 오해가 있으신 것 같은데 그러한 코드는 ibus, uim, imhangul 에도 들어 있는 코드입니다.

> 입력기 제작자분들 스토킹(?) 등 못살게 굴어서 이클립스(?)쪽에서 움직일수있게 해야 하나 울고 싶지만 웃기기도한 복잡 난감하네요. ㅠ.ㅠ

아마 이런 의도로 사람들이 많이 방문하는 우분투 포럼에 땜빵 코드네.. 폄하하면서 입력기 개발자 탓으로 돌리는 글을 작성하신 것 같은데...

저는 피곤하고 부담 느끼면 프로젝트에서 손을 놓으면 놓았지 오픈소스 소비자 갑질에 굴복하여 대신 버그 리포트 하지는 않습니다.

ibus, imhangul, uim, eclipse 프로젝트에는 아무 말씀 안 하시면서 dasom 에만 이러시는 이유가 무엇입니까.

입력기 개발자를 피곤하게 하여 입력기 개발자가 이클립스 프로젝트에 버그를 보내도록 하려는 시도를 중단하시기 바랍니다.

이후 저는 이슈 답변을 하지 않을 것입니다.
상세히 작성해도 각 사용자분들이 어플 쪽에 버그 보고를 하지 않으므로 작성할 필요가 없습니다.
게다가 제가 작성한 답변이 입력기를 폄하하는데 악용되는 사례가 지속적으로 발생하기 때문에 앞으로 이슈에 답변도 하지 않겠습니다.
즉, 다솜 프로젝트에 대한 모든 부분에 대하여 손을 완전히 떼겠습니다.

**Comment by ghost** [comment]
땜빵 코드 안 만들어주면 사람들이 많이 방문하는 우분투 포럼에 개발자 비하하는 글쓰니.. 안 만들어줄 수도 없고...  기껏 만들어줬더니 이제와서 하는 소리가.. 땜빵 코드..
갑질도 정도껏 해야지.

**Comment by madang01** [comment]
p {margin-top:0px;margin-bottom:0px;} 

  호동님께...
 
나비등 한글 입력기 개발을 하신분들 노고는 인정하지만,
후킹이건 모건 잘 돌아가도록 처리를 해주시는것이 근본적인 해결책인지 저는 의문입니다.
잘 돌아가는 입력기가 하나라도 있다면 해당 응용어플 제작자들이 버그 수정에 움직여 줄까요?
저는 아니라고 생각합니다.
물론 후킹 없어도 세월아 내월아 하겠지요. 
그래도 길이 아니면 가지 말아야 하는것이 프로그래밍이라고 생각합니다.
더구나 입력기입니다. 사용자와 OS 를 연결하는 기초중의 기초입니다.
호동님 처럼 입력기 후발주자들이 더 낮은 설계와 품질에 노력을 더 쏟을수있어야 한다고 생각합니다.
그런데 이게 몬가요.
OO 입력기는 되는데 다솜은 안되요 이런 질문에 응대해주기 위해서
이미 입력기 개발을 했던 선배들이 했던 노가다를 후발주자인 호동님도 똑 같은 전철을 밟아야 하는것아닙니까?
제 이런 생각 돌 맞아야 한다면 기꺼이 맞겠습니다.
하지만 제 의사를 꺽고 싶지 않습니다.
 
 --------- 원본 메일 ---------

보낸사람: Hodong Kim notifications@github.com
받는사람 : dasom-im/dasom dasom@noreply.github.com
참조 : Jognhoon Won k9200544@hanmail.net
날짜: 2016년 1월 16일 토요일, 19시 48분 16초 +0900
제목: Re: [dasom] 데비안8 64bit eclipse 에서 수정을 위해서 중간 위치에 한글 한글자 입력후 오른쪽 화살키 입력시 입력한 글자가 사라집니다. (#29)

땜빵 코드 안 만들어주면 사람들이 많이 방문하는 우분투 포럼에 개발자 비하하는 글쓰니.. 안 만들어줄 수도 없고... 기껏 만들어줬더니 이제와서 하는 소리가.. 땜빵 코드..
갑질도 정도껏 해야지.
—
Reply to this email directly or view it on GitHub.

p  {font-size:10pt ! important;font-family:돋움,'굴림',gulim,tahoma,sans-serif ! important;}

**Comment by ghost** [comment]
개발자 비하도 정도껏해야지...
2015년 10월 중순부터... 현재 2016년 1월까지도 지속적으로 발생하는군요.
프로젝트가 유지되려면 이슈 가지고 장난은 치지 말아야 합니다. 기본적으로 지킬 건 지켜야지...
사람들 많이 방문하는 우분투 포럼에 이슈 들먹거리며 개발자 비하하면 답이 없죠..
개발자가 xlib를 모른다는 식으로 써놓지 않나...
내가 옛날에 Xlib, Xt, Xm 어플 개발했던 사람인데..
억울해서 울분이 터지네...
하도 억울해서 회피 코드 만들어줬더니
이제는 땜빵 코드라 그러질 않나...

다음 사전

비하하다1 주요 뜻
①(사람이 스스로를)남보다 낮추다 ②(어떤 사람이 다른 사람을)업신여겨 낮추다 ③(지위가)낮은 상태에 있다﻿

**Comment by ghost** [comment]
그리고 회피코드는 옵션으로 제공하고 있습니다. 맘에 안 들면 옵션을 꺼놓고 사용하면 됩니다. 님께서 이클립스 프로젝트에 버그 보고를 해야지 그거 하기 싫어서 개발자 비하하여 일 시키려고 하는 속셈아잖아요

**Comment by ghost** [comment]
그리고 버그 어플이 10종이 넘는데 그걸 왜 제가 보고해야 한다고 생각하시나요. 저는 님과 소프트웨어 계약을 채결한바 없습니다. 제가 님 노예입니까? 입력기 개발자가 응용 어플에 보고하지 않으면 입력기 개발자를 비하하는게 정상인가요? 거듭 말씀드리지만 이클립스 프로젝트에 보고해주세요. 왜 안 하고 입력기 개발자를 비하하는데요

**Comment by madang01** [comment]
p {margin-top:0px;margin-bottom:0px;} 

 호동님 보세요.
 
제가 우분투에 올린 글 마지막에 올린 추가글은 이클립스와 같은 응용어플이 문제있음에도 
후킹등으로 아무런 문제없이 돌아가도록 만든 입력기 개발자분들에 대한 원망글입니다.
 
아무런 문제없이 돌아가도록 얼마나 노력을 하셨는지 저두 프로그램을 하는 사람으로써 압니다.
맨땅에 헤딩을 하셨을 그분들 생각을 하면 저두 마음이 아련해집니다.
하지만 땜빵은 땜빵일뿐입니다.
왜냐하면 한글 입력기를 먼저 개발한 선배들 처럼 
호동님같은 입력기 후발주자들이 이클립스와 같은 응용어플에서도 잘 돌아가도록  그 노력 그대로 해야 하기때문입니다.
노력이 계승되지 않고 반복되기에 땜빵인것입니다.

##  

제목 :  글 제목: 리눅스 입려기는 속된 말로 땜방 ㅠ.ㅠ
xwindow 에 대해서 잘 모르지만

이것이 프로토콜로 동작을 하는거라

쌍방 잘 동작해야 하겠지요.

다솜 이슈를 보면 제가 제기한 이클립스도 그렇고 이번 Qtcreator 도 그렇고 

x-client 인 이클립스, Qtcreator가 고쳐야 하는 문제를 갖고 있는데

이를 회피하는 코드를 갖는 입력기를 보자니 웃어야 하나 울어야 하나 참... 허망하네요.

프로그램 하는 사람이라면 "땜빵" 이라는 단어가 생각나지 않을까 합니다.

그걸 좋아하는 자랑스러워하는 리눅스에서 보자니 맘 아프네요.

입력기 메카니즘을 알았다면 이런 잘못을 할리가 없기에 

이클립스와 같은 클라이언트들이 무슨 재주로 수정을 할수있는지 버그 제보가 유익할지 의문이 들기에 참 절망적이네요.

과도기라서 그런가..

x-window 대체하는 프로젝트에서는 이런 문제를 갖지 않았으면 하네요.

--------------- 추가
지극히 개인적으로 입력기 선구자들이 땜빵하지 말고 싸워 클라이언트 수정을 이끌었다면
후발주자는 온전히 자기 로직 개선에서만 신경쓰지 않았을까요?
그냥 주저리 주저리 해 봅니다.

**Comment by ghost** [comment]
근본적인 해결책은 이클립스 등의 어플 프로젝트에 버그 리포트를 해서 어플 프로젝트에서 고치도록 해야 합니다. 지금까지 제가 반복적으로 계속 말씀드리고 있습니다.

https://github.com/dasom-im/dasom-jeongeum/issues/15

> qtcreator 프로젝트에 버그리포트 보내주세요.

이렇게 안내를 하고 있습니다.

이클립스 버그에 대해서도 마찬가지로 이클립스 프로젝트에 보고하라고 안내하고 있습니다.

뭐가 문제입니까?

문제가 있다면 사용자분들이 버그 리포트하지 않고 입력기 개발자 탓으로 돌리는 것이 문제죠.

회피 코드를 막상 다 삭제하면 비하글을 쓰시지 않습니까? 그래서 회피 코드를 삭제할 수 없습니다.

그리고 회피 코드는 다솜 프레임워크 메인 소스와 구분이 되어 있고, 옵션으로 제공하므로 맘에 안 들면 꺼놓고 사용하시면 됩니다. 아니면 dasom-gtk 또는 dasom-qt 를 설치하지 않고 사용하셔도 XIM으로 작동이 되므로 그렇게 사용하셔도 되고,
dasom-gtk, dasom-qt 에서 회피 코드를 제거한 후 컴파일하셔서 사용하셔도 됩니다.

입력기 자체는 문제가 없습니다. 입력기에서 할 수 있는 부분은 최대한 해드리고 있으므로 회피 코드가 맘에 들지 않으면 그걸 사용하지 않을 수 있는 여러 옵션(패키지 제거, 옵션 끄기, 코드 삭제 후 컴파일 등)이 있습니다.

거듭 말씀드리지만 근본적인 해결책은 어플에 보고해서 어플에서 고치도록 해야 합니다.
어플 프로젝트에 보내시라고 어플 이슈에 대해 상세히 작성해 드리고 있습니다. 그 내용을 어플 프로젝트에 보내시면 됩니다. 어플 버그 보고까지 제가 할 수는 없는거죠. 버그 어플이 10종이 넘어갑니다. 저한테 이러실게 아니라 저한테 한 것처럼 각 어플 프로젝트에 말씀하시면 어플 개발자가 귀찮아서라도 고쳐줄 겁니다.

**Comment by sukso96100** [comment]
코드 기여자 분들 및 다솜 팀원분들께서 동의 하시는 경우, 지금부터 특정 앱 관련 버그 리포트의 경우, 해당 앱 개발자 또는 개발팀에 버그를 보고했다는 증거가 없으면, 닫아버리고 토론 잠그도록 하겠습니다.

**Comment by sukso96100** [comment]
특정 앱 관련 버그 리포트 이슈는, 해당 앱 개발자 또는 개발팀에 버그를 리포트했다는 증거를 dasom-im/\* 에 이슈를 생성하실때 첨부하지 않으시면, 해당 이슈를 닫고 이슈의 토론을 닫기로 결정되었습니다. 이 이슈의 토론부터 잠그도록 하겠습니다.
