### ISSUE TITLE
터미널에서 sudo gedit 실행시 한영 바꿈이 안되네요.

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom#30]
_From @iyagicom on November 14, 2015 9:0_

노트북이고 alt(한/영)키를 쓰고 있고 우분투 15.04입니다.
sudo gedit /usr/share/applications/android-studio.desktop 로 gedit를 불러와서 한영바꿀려면 안되네요

_Copied from original issue: cogniti/dasom#25_

**Comment by ghost** [comment]
입력기 버그가 아닙니다.
데비안 jessie 에서 재현되지 않습니다.
우분투 15.10 에서 재현됩니다.
우분투에 버그 리포트 보내시기 바랍니다.

**Comment by cogniti** [comment]
타 입력기에서도 이러한 현상이 발생되는 것 같습니다.
imhangul 로도 테스트해 보시고 결과 알려주세요.

**Comment by ghost** [comment]
@iyagicom
타 입력기에서도 이러한 현상이 발생되는 것 같습니다.
imhangul 로도 테스트해 보시고 결과 알려주세요.

**Comment by ghost** [comment]
@iyagicom
우분투 프로젝트 쪽에 fcitx sudo gedit, ibus sudo gedit 이런 식으로 검색해보셔서 제게 링크 좀 알려주세요. 웹 문서 검색해보니 DBus 문제 때문에 fcitx sudo gedit 마찬가지 현상이 나타난다는 것 같은데, 다솜은 DBus 방식이 아니라서 그런 문제가 발생하는 것이 이해가 되지 않습니다. 다솜이 설정을 읽어오는 부분이 있는데, 이 부분이 GSettings 내부적으로 DBus 통신하는지는 모르겠습니다.
imhangul 은 통신 구조도 아니고 DBus 구조도 아니니 imhangul 로 꼭 테스트해보시고... 결과를 알려주세요. 저는 데비안 사용 중이고 이 문제를 겪지 않아서 imhangul 로 테스트해본들 의미가 없어서 그렇습니다. 버추얼박스에 imhangul 설치해봤는데 imhangul 이 작동 중인지 아닌지 확인이 되질 않아서요.
이 글을 보시는 다른 분들도 imhangul 설치하여 sudo gedit 테스트 부탁드리며 결과를 알려주세요.

**Comment by ghost** [comment]
@iyagicom
imhangul 설치하여 sudo gedit 테스트 결과 마찬가지 현상이 나타납니다.
imhangul 은 비통신 방식이며 DBus 통신을 하지 않습니다.
확실하게 우분투 문제로 보입니다.  우분투에 버그 리포트 보내시기 바랍니다.
