### ISSUE TITLE
표시기 정보(About)에 다솜 작명하시분 추가하고 싶습니다

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom#32]
권수혁님이 다솜이란 이름을 붙여주셨습니다.

이걸 영작해서... 다솜 입력기 표시기 정보(About) 에 넣고 싶습니다.
제가 영작 능력이 부족하여 못 넣고 있는데,

영어 좀 하시는 분이 영작 좀 해주십시오.﻿

**Comment by sukso96100** [comment]
The name of this input method, "dasom" was named by Suhyeok Gwon. 
이 입력기의 이름, "다솜" 은 권수혁에 의해 명명되었다.

The name, "dasom" was named by Suhyeok Gwon.
그 이름, "다솜" 은 권수혁에 의해 명명되었다.

"dasom" was named by Suhyeok Gwon.
"다솜" 은 권수혁에 의해 명명되었다.

**Comment by ghost** [comment]
Dasom was named by Suhyeok Gwon. 이렇게 하면 되겠군요.
감사합니다.
