### ISSUE TITLE
Zorin os 10 용으로.. 패키징을 해주실 수 있을까요?

### ISSUE THREAD

**Issue by onionmixer** [dasom-im/dasom#35]
우분투 15.04 기반의 배포판입니다.

qtbase-abi 관련으로 1.1 의 15.10 을 대상으로 하는 버전이 설치가 안되더군요..
(정확히는 qt 관련된 부분만 설치가 안되는것 같습니다만...)

혹시 zorin os 10 또는 우분투 15.04 기반으로 compile 된 deb 패키지를 요청드려도 될까요?

ps. 이전 프로젝트쪽에 issue 를 올려서 이쪽으로 하나 더 올려 봅니다. issue 때문에 github 을 가입하게 될줄은 생각도 못했네요 ㅎㅎㅎ

**Comment by ghost** [comment]
몇 비트인가요?

**Comment by ghost** [comment]
우분투 15.04 용 32비트, 64비트 파일 올려놓았습니다.
https://github.com/dasom-im/dasom/releases/tag/1.1
https://github.com/dasom-im/dasom-jeongeum/releases/tag/1.1
deb 파일은 1.1 까지만 제공합니다. 개발 시간 확보의 일환으로 다음 버전부터는 deb 파일을 제공하지 않습니다.

deb 패키지 만드는 방법을 버전 1.1, 64비트 기준으로 알려드리겠습니다.
https://github.com/dasom-im/dasom/releases/latest
https://github.com/dasom-im/dasom-jeongeum/releases/latest
에서 소스코드를 다운받아서 압축을 풀고

```
cd dasom-1.1
dpkg-checkbuilddeps
```

없다는 패키지 모두 설치 후에

```
dpkg-buildpackage -b
cd ..
sudo dpkg -i dasom_1.1_amd64.deb
```

```
cd dasom-jeongeum-1.1
dpkg-checkbuilddeps
```

없다는 패키지 모두 설치 후에

```
dpkg-buildpackage -b
cd ..
sudo dpkg -i dasom-jeongeum_1.1_amd64.deb
```
