### ISSUE TITLE
Caps Lock 키 상태를 다솜 표시기에 표시

### ISSUE THREAD

**Issue by ghost** [dasom-im/dasom#37]
제 키보드는 Caps Lock 키를 눌렀을 때 키보드에 LED 가 켜지나 잘 보이질 않습니다.
그래서 다솜 표시기에서 Caps Lock가 켜졌을 때 이를 표시하는 기능을 추가하고자 합니다.
아이콘 색상을 바꾸는 방법을 생각하고 있습니다.
예를 들자면, 테두리 색깔이나 바탕 색깔.
다른 분들의 의견을 듣고 싶습니다.

**Comment by sukso96100** [comment]
표시기 보다는, 커서 쪽에 조그마한 팝업으로 "Caps Lock On" 이런씩으로 잠깐 나타나게 하는것은 어떤가요? 표시기 아이콘을 통해서 표시하면 Caps Lock 상태만 표시하면 괜찮지만, Num Lock 상태까지 표시하면 표시기가 아이콘이 복잡해 질것 같아요.

**Comment by minwook-shin** [comment]
지금 ko,en나오는 글자를 caps lock on일때 대문자로 바꾸는것을 건의합니다.

**Comment by ghost** [comment]
오... 두 분다 아주 좋은 의견이네요.

**Comment by namwonkeun** [comment]
저는 caps lock on이 되면 키보드 처럼 연녹색으로 아이콘 글자가 바뀌었으면 좋겠어요.

**Comment by ghost** [comment]
이 기능은 https://developer.gnome.org/libnotify/ 를 이용하여 nimf-indicator 에 구현되었습니다.
Caps Lock 를 on / off 할 때 데스크탑에 알림 메시지가 표시되도록 하였습니다.
사용자 기호에 따라 nimf-settings 에서 Indicator (표시기) 메뉴를 클릭하여 옵션을 on / off 할 수 있습니다.
감사합니다.
