### ISSUE TITLE
Sublime Text 3 에서 일종의 끝글자 문제?

### ISSUE THREAD

**Issue by nemonein** [dasom-im/dasom#40]
안녕하세요.
우분투 14.04(64bit) 사용 중이고, 다솜은 PPA 최신판 사용중입니다.
Sublime Text 3  에서 한국어 입력은 됩니다. 다만 두가지 정도 아쉬운 부분이 있는데요.
이 문제는 아마도 SLT3 의 문제라고 생각되긴 합니다만, 한번 말씀은 드려봅니다.

첫번째는, 한글이 조합되는 과정이 보이지 않는다는 점입니다. '한'을 쓸 때 ㅎ 하 한 이런 식으로 보이는 것이 아니고, '한'을 완성한 다음에야 글자가 입력됩니다. 이 때문에 오타가 늘어나는 것도 같습니다.

두번째는, 뭐라 표현해야 할 지 모르겠습니다만, 예를 들면 이렇습니다.
'한국어'라는 단어를 입력한다고 했을 때, 마지막 '어'자를 완성시키기 위해서는 공백/특수문자를 입력하거나 아니면 뒤에 다른 글자를 또 입력해야만 합니다. 이 현상을 피하기 위해서 저는 보통 마지막 글자 뒤에 오른쪽 방항키를 입력하는 습관이 있는데, 다솜에선 이것도 통하지 않습니다.

엔터도 듣지 않는데요. '한국어'를 입력하고 엔터를 누르면 '한국'까지만 입력되고 '어'는 숨어(?)있게 됩니다.
이때 커서를 다른 곳으로 옮기고 Space/특수문자 등의 키를 입력하면 그곳에 '어'와 함께 Space/특수문자 등이 같이 입력됩니다.

현재 제가 시험해본 바로, SLT3 에서 한국어 입력이 가능한 입력기는 총 3 종입니다.
Scim, Uim, 다솜. 이것들인데요.
Uim 과 다솜은 비슷한(동일한?) 결과를 보여줍니다.
Scim 도 비슷하기는 한데, Scim 은 오른쪽 방향키 편법이 통합니다. 즉, '한국어'를 모두 입력한 후, 오른쪽 방향키를 누르면 '한국어'가 오롯이 잘 입력됩니다.

확인부탁드리겠습니다.
고맙습니다.

**Comment by ghost** [comment]
확인해보았는데 Sublime Text 문제입니다.
1. Sublime Text 에 preedit string 를 그려주는 부분이 없을 것을 추정됩니다.
2. 화살표키 말고, 컨트롤키나 스페이스를 누르시면 preedit string 이 commit 됩니다. 화살표키 눌렀을 때 commit 하도록 dasom-jeongeum 코드를 변경하는 방법도 있지만, 별 의미 없습니다. 응용 프로그램에서 처리를 해야 하는 부분입니다.
3. 엔터키도 2번과 마찬가지입니다. 화살표키, 엔터키를 눌렀을 때 `dasom_jeongeum_filter_event()` 함수가 `FALSE` 값을 리턴합니다. 그 키 값을 입력기가 소비하지 않았으니 응용 프로그램에서 처리하라는 의미인데, 응용 프로그램에서 처리하지 않아서 발생하는 문제입니다.

Sublime Text 측에 문의하셔야 되겠습니다.

**Comment by ghost** [comment]
Sublime Text 가 `preedit-changed` 신호를 받으면 `gtk_im_context_get_preedit_string()` 함수를 호출하여 조합 중인 문자를 받아서 처리해야 하는데, `gtk_im_context_get_preedit_string()` 함수를 호출하지 않습니다.

**Comment by nemonein** [comment]
답변 고맙습니다.
Sublime Text 측에 문의는.. 해도 별 소용이 없을 것 같습니다.
이미 몇 번(제가 한 것은 아니지만) 보고가 됐지만, 별 움직임이 없었기에..
동양권 언어까지 지원할 여력이 없는 듯 합니다. (동양에서 구매한 실 사용자가 많지 않은 탓일지도 모르겠군요.)

아무튼, 고생하셨습니다.
고맙습니다.

**Comment by ghost** [comment]
제가 Sublime Text 측의 게시판에서 위의 내용에 대해 검색해보았지만 찾을 수 없었습니다. Sublime Text 측에 문의하셔야 합니다. 아무튼, 다솜 문제가 아니므로 이슈를 닫겠습니다.

**Comment by nemonein** [comment]
혹시나 하여 덧붙입니다.
이미 보고가 됐다고 말씀드렸던 것은, 저런 내용으로 되었다는 걸 말씀드린 것은 아니었구요.
그저, SLT3 에서 동양권언어(주로 중국어와 일본어에 대한 내용이었던 걸로 기억됩니다만..)를 입력할 때 문제가 있다는 정도로 보고가 된 걸 봤다는 내용이었습니다. 한국어를 특정지어 보고한 글은 본 기억이 없습니다.
어쨌든 이미 SLT2 부터 입력에 대한 문제는 회자되고 있는데, 여전히 마찬가지군요.
그런 글타래에서 동양권 언어에 대한 지원이 미비하다.. 는 글을 봤던 것 같습니다.

아무튼, 문제는 SLT 로군요.
