### ISSUE TITLE
보미(동영상 재생기)에서 Space 가 무시되는(?) 문제.

### ISSUE THREAD

**Issue by nemonein** [dasom-im/dasom#42]
안녕하세요.
우분투 14.04, 보미(https://github.com/xylosper/bomi) 0.9.11 을 사용하고 있습니다.
보미에서 영상을 일시정지/재생하는 키가 'Space' 인데요. 이것이 작동하지 않습니다.
기본값으로 Space 가 지정되어 있는데, 보미의 '환경설정' - '유저 인터페이스' - '키보드 단축키' 에서 단축키를 'Space'로 설정하려 하면 Space 키를 입력해도 반응이 없습니다. 다른 키들(Ctrl-P 등)은 제대로 입력이 됩니다.

살펴봐주시면 좋겠습니다.
안타까운 것은 현재 보미 개발자께서 개발을 중단하고 계시다는 점인데..
보미의 문제로 밝혀지면 그냥 감수하고 다른 키로 쓸 수밖에 없겠네요.

아무튼 부탁드리겠습니다.
고맙습니다.

**Comment by ghost** [comment]
타 입력기로는 어떤가요?
2015. 12. 14. 오전 11:25에 "nemonein" notifications@github.com님이 작성:

**Comment by ghost** [comment]
보미 쪽에서는 뭐라고 하던가요?

**Comment by ghost** [comment]
이 문제는 가상 머신에서 테스트하기가 곤란하니 다른 분들이 확인을 좀 해주세요.

**Comment by nemonein** [comment]
iBus, Fcitx 에서 이상없습니다.
우분투 14.04, 15.10 에서 확인한 결과입니다.
다른 입력기는 확인해보지 않았습니다.

그리고, 말씀드렸다시피 현재 보미는 개발이 중단된 상태입니다. 개발자께서 지난 7월, 상황이 좋지 않아서 당분간 신경을 쓸 수 없다는 말씀을 남기셨고, 이후 깃헙, 트위터, 홈페이지 모두 아무런 변화가 없습니다.
따라서 보미쪽엔 문의하지 않았습니다.

**Comment by ghost** [comment]
보미의 경우 qt5 를 사용하는군요... focus 부분에서 보미 또는 다솜에 문제가 있을 것 같습니다.

**Comment by ghost** [comment]
This issue was moved to dasom-im/dasom-qt#2
