### ISSUE TITLE
한자창에 표시되는 한자(또는 특수문자)가 네 글자만 표시되는 때가 있습니다.

### ISSUE THREAD

**Issue by nemonein** [dasom-im/dasom#48]
이게 어떤 경우에 이런 현상이 나타나는지는 모르겠습니다.
일반적인 경우, 제 컴퓨터 환경에서 한자창의 목록에 한자 후보가 11글자 정도 나타납니다. 이게 정상적인 상태라고 보여집니다.

그런데, 가끔, 한자창 목록에 네 글자만 나타날 때가 있습니다. (어떨 때 이렇게 되는지 재현이 어렵네요.)
예를 들어 '한'을 입력하고 한자키를 누르면 나타나는 한자창에 한자 후보가 네 글자만 보여집니다.
네 글자만 나타나서 큰 문제가 되는 것은 아니지만, 이럴 경우 스크롤이 제대로 안된다는 것이 문제입니다.

'한'을 입력했을 때 나타나는 후보 한자 목록 네 글자는 '韓漢寒限' 인데요. 다섯번째 글자를 보기 위해 방향키를 사용해서 限 아래로 커서를 내리면, 그 다음 글자가 표시되는 것이 아니고 그냥 저 네 글자에 머물러 있습니다.

방향키를 계속 누르면 '罕' 이 표시되면서 새로운 한자 후보목록이 나타나는데요. 이 罕 자는 다섯번째 '한'에 해당하는 한자가 아니고 11번째 한자입니다.
미루어 짐작해보자면, 창에는 (어떤 이유에서든) 네 글자만 표시가 되지만, 프로그램은 11글자를 모두 표시한 것으로 오작동하는 것 같습니다.

정리하자면, 가끔 한자창에 네 글자만 표시되는 경우가 있고, 이럴 때는 스크롤도 제대로 작동하지 않는다는 것입니다.
이것은 한자만이 아니라 특수문자 입력(예를 들어 'ㄱ'을 입력하고 한자키)시에도 동일합니다.
확인 부탁드립니다.

아울러, 작업하고 계시리라 생각하지만, 기본적으로 보여지는 글자의 개수도 조정 가능하면 좋겠습니다.

**Comment by ghost** [comment]
후보가 10개 나오도록 의도하였는데, 어떤 상황에서는 11개가 나오기도 합니다.
윈도가 그려졌을 때 크기를 받아서 스크롤러 크기를 계산하도록 의도하였는데,
잘못된 크기값이 나오기도 합니다. 원인 파악을 하지 못하였습니다.

**Comment by ghost** [comment]
관련 이슈
https://github.com/dasom-im/dasom/issues/22
https://github.com/dasom-im/dasom/issues/47
https://github.com/dasom-im/dasom/issues/49
우분투 14.04 에서 발생하는 현상입니다. 아마 GTK 버그로 추정됩니다.
데비안 jessie, 우분투 15.04, 우분투 15.10 에서는 발생 빈도가 희박합니다(거의 발생하지 않습니다.).

타 입력기들(ibus, imhangul, nabi)처럼 왼쪽 스크롤러를 만들지 말고, 화살표키 또는 PgUp, PgDn 등으로 페이지 단위로 스크롤하도록 하여 이 문제를 해결할 수 있습니다.
