### ISSUE TITLE
한자창 기본 커서 위치 문제.

### ISSUE THREAD

**Issue by nemonein** [dasom-im/dasom#49]
한자를 연달아 입력할 때, 이전 입력한 한자의 위치에 커서가 자리잡는 현상이 있습니다.
예를 들어, 微笑 를 입력하려 한다면, 미를 입력하고 한자키를 눌러 6번째 후보에 있는 微 를 선택합니다.
그리고 소를 입력하고 한자키를 눌렀을 때, ('소'에 해당하는 한자가 제대로 보여지지 않는 현상은 #47 에서 말씀드렸습니다.) 그림처럼 6번째 한자 素에 커서가 자리잡고 있습니다. 이 상태에서 그냥 엔터를 누르면 素 가 입력되는 것은 아니고, 첫번째 후보인 小 가 입력됩니다.

![_](https://cloud.githubusercontent.com/assets/5688288/12073191/be2c9f62-b152-11e5-919b-85e0a0685982.png)

사실 위의 사진은 '조작'된 것이긴 합니다.
실제로 보여지는 그림은 아래와 같습니다.
![_ _2](https://cloud.githubusercontent.com/assets/5688288/12073207/8a9a8cb6-b154-11e5-9c05-e22a47f2091d.png)

확인 부탁드립니다.

**Comment by ghost** [comment]
한자창 갱신 문제입니다.
중복 이슈입니다. https://github.com/dasom-im/dasom/issues/22

**Comment by ghost** [comment]
debian jessie 에서는 이렇게 나옵니다. 이렇게 나오도록 의도하였습니다.
10개의 아이템이 나옵니다.
![screenshot from 2016-01-02 14 35 35](https://cloud.githubusercontent.com/assets/9195462/12073333/45eb2490-b15e-11e5-87c9-7b0530863365.png)

```
hodong@debian:~$ dpkg --list | grep libgtk-3
ii  libgtk-3-0:amd64                      3.14.5-1+deb8u1                      amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                          3.14.5-1+deb8u1                      amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common                       3.14.5-1+deb8u1                      all          common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64                    3.14.5-1+deb8u1                      amd64        development files for the GTK+ library
ii  libgtk-3-doc                          3.14.5-1+deb8u1                      all          documentation for the GTK+ graphical user interface library
```
