### ISSUE TITLE
Enpass(Password Manager) 에서 한/영 전환 불가.

### ISSUE THREAD

**Issue by nemonein** [dasom-im/dasom#54]
안녕하세요.
새해에도 늘 건강하시길 기원합니다.

Enpass(https://www.enpass.io/) 라는 비밀번호 관리자가 있는데요.
리눅스 데스크탑 판에서 한/영 전환이 되질 않습니다.
아마도 Enpass 문제일 가능성이 높습니다. Fcitx, ibus 등에서도 모두 안되거든요.

그래도 한번 살펴봐주시고, 문제점을 짚어 주시면 Enpass 쪽에 건의해보도록 하겠습니다.
사실 작년엔가 Enpass 에 얘기를 하긴 했었는데, 알겠다고만 하고 아직까지 고쳐진 것이 없네요.

정리하자면..
Enpass 5.0.2, 우분투 14.04/15.10 환경에서, 다솜(Fctix, iBus)의 한/영 전환 기능이 작동하지 않습니다.

확인 부탁드립니다.
고맙습니다.

**Comment by ghost** [comment]
ibus, fcitx, dasom 등에서 안 되는 어플은 gtk im api, qt im api, xim 등의 입력 api를 사용하지 않아서 그럴 겁니다. 어플 프로젝트에 말씀해주세요

**Comment by nemonein** [comment]
흠...
Enpass 측에 문제 보고를 하고 왔더니.. 뭔가 심각한 일이 벌어진 모양이군요.
원만히 잘 해결되시길 바라겠습니다.

응원하고 있습니다!
추운 날씨에 건강 유의하시길 바라며..
