### ISSUE TITLE
우분투 글은 우분투에서 답글 다실거지 이곳에 그것도 닫은 이슈에서 하신이유가 무엇인가요?

### ISSUE THREAD

**Issue by madang01** [dasom-im/dasom#55]
우분투 글은 우분투에서 답글 다실거지 
이곳에 그것도 2015년 11월 21일에 닫은 이슈에서 하신이유가 무엇인가요?
해당 쓰레드는 이클립스 문제라고 답변 주셔서 제가 닫았거나 호동님이 닫아 주셨거든요.
우분투에 제가 쓴글은 해당 쓰레드랑 아무런 상관없는 글이거든요.
도대체 왜 그러시는건가요?
궁굼해서 질문해 봅니다.

------------- 아래는 분명 2015년 11월 21일에 제가 닫거나 호동님이 닫은 쓰레드입니다.
제목 : 데비안8 64bit eclipse 에서 수정을 위해서 중간 위치에 한글 한글자 입력후 오른쪽 화살키 입력시 입력한 글자가 사라집니다.  #29 

this issue in dasom-im/dasom-jeongeum on Nov 21 2015  Closed

**Comment by sukso96100** [comment]
호동님께 질문하시는 것이라면, 여기에 이슈 열지 마시고, 호동님께 직접 연락 드리시기 바랍니다. 호동님께서 어제자로 GitHub 탈퇴 하셔서 여기에 이슈 열어보셔봤자 호동님께 답변을 받지 못합니다.
