### ISSUE TITLE
다솜 1.2.2버전 이후 브라우저 입력 불가 문제

### ISSUE THREAD

**Issue by loggerJK** [dasom-im/dasom#63]
다솜 입력기를 1.2.2로 업데이트 한 후 크롬과 파이어폭스에서 아무 입력도 먹히지 않는 버그가 있습니다.
터미널이나 유니티 대시 등 다른 애플리케이션에서는 정상 작동합니다
리눅스 민트 17.3 로사와 우분투 14.04.3 에서 버그 확인했습니다

**Comment by loggerJK** [comment]
http://egloos.zum.com/nemonein/v/5288353
임시 해결법은 위 블로그 파일에서 다솜 패키지만 dpkg -i 명령으로 강제 설치하여 덮어씌우면 됩니다

**Comment by sukso96100** [comment]
다솜 API 변경이 있어서 그럴 겁니다. dasom-gtk, dasom-qt, dasom-jeongeum 새 버전 패키지 나오면 설치 하신 후 다시 해 보시거나, 기다리시기 어려우시면 직접 dasom-gtk, dasom-qt, dasom-jeongeum 컴파일 해서 설치 하시면 되겠습니다.

**Comment by sukso96100** [comment]
패키지 올라왔으니 새 패키지 설치 해보시기 바랍니다.

**Comment by loggerJK** [comment]
감사합니다
