### ISSUE TITLE
크로미움이 실행이 안됩니다.

### ISSUE THREAD

**Issue by panuscript** [dasom-im/dasom#71]
ubuntu mate 배포판 16.04 버전입니다.
dasom을 사용하면 아래와 같은 메세지가 나오면서 실행이 되지 않고,
다른 입력기로 전환하고 dasom을 제거하면 실행이 잘 되었습니다.

[libprotobuf FATAL ../../third_party/protobuf/src/google/protobuf/stubs/common.cc:61] This program requires version 2.6.0 of the Protocol Buffer runtime library, but the installed version is 2.5.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-pkdHET/mir-0.21.0+16.04.20160330/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)

**Comment by ghost** [comment]
확인해보았는데, 다솜 버그가 아닙니다.
우분투에 들어 있는 chromium-browser 버그입니다.

해결책은...
구글 크롬 브라우저를 사용하거나..
https://www.google.com/chrome/browser/desktop/index.html

데비안 Jessie 에 있는 chromium 을 사용하는 방법(64비트 기준)이 있습니다.
https://packages.debian.org/jessie/chromium
https://packages.debian.org/jessie/amd64/chromium/download
데비안 Jessie 현재 버전의 chromium 은 아래 패키지를 요구합니다. 요구 패키지는 미래에 변경될 수 있습니다.
https://packages.debian.org/jessie/libjpeg62-turbo
https://packages.debian.org/jessie/amd64/libjpeg62-turbo/download

자세한 내용은 https://github.com/cogniti/nimf/issues/3 를 참고하시기 바랍니다.

**Comment by panuscript** [comment]
감사합니다! 문제 해결했습니다!
chromium-browser 지우고 구글 크롬 설치하니 문제없이 작동합니다.
