### ISSUE TITLE
Lubuntu 16.04에서 다솜 한글 입력

### ISSUE THREAD

**Issue by parkmino** [dasom-im/dasom#73]
며칠 전에 Lubuntu 16.04 64비트 버전을 새로 설치했습니다.
시스템 기본인 fcitx는 한글 입력이 되는데, 다솜 한글이 안되네요.
혹시 조언을 구해도 될는지요?

다솜을 우분투 PPA에서 설치하고, im-config로 설정은 했습니다.

**Comment by ghost** [comment]
터미널 열어서

export | grep GTK
export | grep QT
export | grep XMOD

결과를 올려주세요.
2016. 6. 10. 오전 7:55에 "Min-ho Park" notifications@github.com님이 작성:

**Comment by parkmino** [comment]
parkmino@ubuntu:~$ export | grep GTK
declare -x GTK_IM_MODULE="dasom"
parkmino@ubuntu:~$ export | grep QT
declare -x QT4_IM_MODULE="dasom"
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE="dasom"
declare -x QT_LINUX_ACCESSIBILITY_ALWAYS_ON="1"
parkmino@ubuntu:~$ export | grep XMOD
declare -x XMODIFIERS="@im=dasom"

2016-06-10 8:49 GMT+09:00 Hodong Kim notifications@github.com:

**Comment by ghost** [comment]
설정은 이상 없는 것 같습니다. dasom-jeongeum 을 설치했는지 확인해보세요.
2016. 6. 10. 오전 8:53에 "Min-ho Park" notifications@github.com님이 작성:

**Comment by parkmino** [comment]
네, 설치는 메뉴얼대로 한 것 같은데, 입력이 안되네요.

parkmino@ubuntu:~$ dpkg -l dasom*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  dasom          1.2.3-1~xeni amd64        Input Method Framework
ii  dasom-gtk      1.2.2-1~xeni amd64        GTK+ IM modules for Dasom
ii  dasom-jeongeum 1.2.2-1~xeni amd64        Korean language engine module for
ii  dasom-qt       1.2.6-1~xeni amd64        Qt IM modules for Dasom

**Comment by ghost** [comment]
버추얼박스에 lubuntu-16.04-desktop-amd64.iso 설치한 후
https://wiki.ubuntu-kr.org/index.php/Dasom 에 나온대로 했는데
한글 입력 잘 됩니다.
![screenshot from 2016-06-10 21 22 59](https://cloud.githubusercontent.com/assets/17453239/15964120/dc5399fa-2f51-11e6-9207-39c28983cd46.png)

**Comment by ghost** [comment]
키 설정에 문제가 있는 것은 아닌지 확인해보세요.
https://wiki.ubuntu-kr.org/index.php/Dasom 에 키 설정하는 내용이 있으니 다시 확인하시기 바랍니다.

**Comment by parkmino** [comment]
오~ 이렇게까지 신경을 써 주시다니 고맙습니다!
역시 말씀하신대로 키보드 설정을 하니 한글이 제대로 입력이 됩니다.
이 글도 다솜으로 입력하고 있습니다.

다시 한 번 감사드립니다!

2016-06-10 21:44 GMT+09:00 Hodong Kim notifications@github.com:
